[package]
name = "lending"
type = "contract"
authors = [""]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.81.0", directory="noir-projects/aztec-nr/aztec" }
authwit = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.81.0", directory="noir-projects/aztec-nr/authwit" }
token = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.81.0", directory="noir-projects/noir-contracts/contracts/token_contract" }
token_bridge = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.81.0", directory="noir-projects/noir-contracts/contracts/token_bridge_contract" }
keccak256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/keccak256" }
