[package]
name = "TokenBridge"
type = "contract"
authors = [""]

[dependencies]
aztec = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.81.0", directory="noir-projects/aztec-nr/aztec" }
token = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.81.0", directory="noir-projects/noir-contracts/contracts/token_contract" }
token_portal_content_hash_lib = { git="https://github.com/AztecProtocol/aztec-packages/", tag="v0.81.0", directory="noir-projects/noir-contracts/contracts/token_portal_content_hash_lib" }
